### ISSUE TITLE
how do you do user input in bash?

### ISSUE THREAD

**Issue by IcingHackz** [IcingHackz/learning-js#1]

**Comment by darkdarcool** [comment]
You do
`read myvar`

**Comment by darkdarcool** [comment]
but in js… maybe use my module idk…
```
const e = require(“consoleassister”)
console.log(“enter your username”)
username = e.readline(“> ”)
console.log(`Hello ${username}`)
```

**Comment by zplusfour** [comment]
In Bash, use `read`
In js use [this](https://npmjs.com/readline)

**Comment by zplusfour** [comment]
and bruhh the repo name is `learning js` but the most usef language ia Python lol

**Comment by IcingHackz** [comment]
~~lmfao why did 2 people answer this question.~~
Thx @darkdarcool

Thx @zplusfour 
lol

**Comment by darkdarcool** [comment]
Lol your welcome

**Comment by zplusfour** [comment]
maybe bc we're following you ;)
And ur welcome 😉

**Comment by IcingHackz** [comment]
ok lol
:D

**Comment by IcingHackz** [comment]
@darkdarcool @zplusfour another question: how do you do `if` statements?

**Comment by darkdarcool** [comment]
is bash:

``` bash
echo -n "Enter a number: "
read VAR

if [[ $VAR -gt 10 ]]
then
  echo "The variable is greater than 10."
fi
```
and In js

``` javascript
var e = 10;
if (e == 10) {
  console.log("e");
}
else {
  console.log("LOL");
}
```

**Comment by IcingHackz** [comment]
ok thx a lot :)

**Comment by darkdarcool** [comment]
Your welcome:)

**Comment by zplusfour** [comment]
eeeeee
I don't receive mentions if the issue is closed :)))

**Comment by IcingHackz** [comment]
lol
